import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
const space = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={space.variable}>
      <body className={"overflow-x-hidden"}>{children}</body>
    </html>
  );
}
